# Servidor
server.port=8080
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true

# Banco de dados
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=supportbot;encrypt=false
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto=update

# Groq API
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.api.key=${GROQ_API_KEY}
groq.api.model=llama-3.1-8b-instant

# CORS (permitir chamadas do Angular)
spring.web.cors.allowed-origins=http://localhost:4200
